# Copyright The Linux Foundation and each contributor to LFX.
---
site_name: LFX Landing and Launch Page
site_description: This is the new rebranding/code hosting site for https://lfx.linuxfoundation.org/
plugins:
  - techdocs-core
